#!/usr/bin/env python
# EASY-INSTALL-ENTRY-SCRIPT: 'Alakazam==0.0','console_scripts','initialize_Alakazam_db'
__requires__ = 'Alakazam==0.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('Alakazam==0.0', 'console_scripts', 'initialize_Alakazam_db')()
    )
